/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic.allowances;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.core.Suppliers;
import com.basistheory.core.pagination.SyncPagingIterable;
import com.basistheory.resources.agentic.allowances.credentials.CredentialsClient;
import com.basistheory.resources.agentic.allowances.rails.RailsClient;
import com.basistheory.resources.agentic.allowances.requests.AllowancesErrorsRequest;
import com.basistheory.resources.agentic.allowances.requests.AllowancesListRequest;
import com.basistheory.resources.agentic.allowances.requests.AllowancesUpdateRequest;
import com.basistheory.resources.agentic.allowances.requests.CreateAllowanceRequest;
import com.basistheory.types.Allowance;
import com.basistheory.types.AllowanceVerificationResponse;
import com.basistheory.types.SharedPaymentProviderError;
import com.basistheory.types.VerifyAllowanceRequest;
import java.util.function.Supplier;

public class AllowancesClient {
    protected final ClientOptions clientOptions;

    private final RawAllowancesClient rawClient;

    protected final Supplier<RailsClient> railsClient;

    protected final Supplier<CredentialsClient> credentialsClient;

    public AllowancesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAllowancesClient(clientOptions);
        this.railsClient = Suppliers.memoize(() -> new RailsClient(clientOptions));
        this.credentialsClient = Suppliers.memoize(() -> new CredentialsClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAllowancesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Lists allowances for the current tenant. Defaults to active, unexpired resources; use <code>status=all</code> for a complete Portal history. Results can be scoped to one payment method, and server-side page filling prevents sparse pages when filtering by status.
     */
    public SyncPagingIterable<Allowance> list() {
        return this.rawClient.list().body();
    }

    /**
     * Lists allowances for the current tenant. Defaults to active, unexpired resources; use <code>status=all</code> for a complete Portal history. Results can be scoped to one payment method, and server-side page filling prevents sparse pages when filtering by status.
     */
    public SyncPagingIterable<Allowance> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Lists allowances for the current tenant. Defaults to active, unexpired resources; use <code>status=all</code> for a complete Portal history. Results can be scoped to one payment method, and server-side page filling prevents sparse pages when filtering by status.
     */
    public SyncPagingIterable<Allowance> list(AllowancesListRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Lists allowances for the current tenant. Defaults to active, unexpired resources; use <code>status=all</code> for a complete Portal history. Results can be scoped to one payment method, and server-side page filling prevents sparse pages when filtering by status.
     */
    public SyncPagingIterable<Allowance> list(AllowancesListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Create a spending allowance from a payment method. Supply <code>merchant</code> to scope the mandate to one merchant, or omit it to leave the allowance open and name a merchant on each credential request instead. The payment method must have at least one enabled rail; otherwise the request returns <code>NO_ACTIVE_RAILS</code>.
     */
    public Allowance create(CreateAllowanceRequest request) {
        return this.rawClient.create(request).body();
    }

    /**
     * Create a spending allowance from a payment method. Supply <code>merchant</code> to scope the mandate to one merchant, or omit it to leave the allowance open and name a merchant on each credential request instead. The payment method must have at least one enabled rail; otherwise the request returns <code>NO_ACTIVE_RAILS</code>.
     */
    public Allowance create(CreateAllowanceRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    public Allowance get(String allowanceId) {
        return this.rawClient.get(allowanceId).body();
    }

    public Allowance get(String allowanceId, RequestOptions requestOptions) {
        return this.rawClient.get(allowanceId, requestOptions).body();
    }

    /**
     * Cancel an allowance so new credentials cannot be created from it. Network-side purchase instructions held by its rails are cancelled with the provider.
     */
    public void delete(String allowanceId) {
        this.rawClient.delete(allowanceId).body();
    }

    /**
     * Cancel an allowance so new credentials cannot be created from it. Network-side purchase instructions held by its rails are cancelled with the provider.
     */
    public void delete(String allowanceId, RequestOptions requestOptions) {
        this.rawClient.delete(allowanceId, requestOptions).body();
    }

    /**
     * Updates one or more mutable fields by changing the provider-side mandate first, then committing the same amount, prompt, and expiry locally. Mints are blocked while the update is in flight, and an empty request body is rejected.
     */
    public Allowance update(String allowanceId) {
        return this.rawClient.update(allowanceId).body();
    }

    /**
     * Updates one or more mutable fields by changing the provider-side mandate first, then committing the same amount, prompt, and expiry locally. Mints are blocked while the update is in flight, and an empty request body is rejected.
     */
    public Allowance update(String allowanceId, RequestOptions requestOptions) {
        return this.rawClient.update(allowanceId, requestOptions).body();
    }

    /**
     * Updates one or more mutable fields by changing the provider-side mandate first, then committing the same amount, prompt, and expiry locally. Mints are blocked while the update is in flight, and an empty request body is rejected.
     */
    public Allowance update(String allowanceId, AllowancesUpdateRequest request) {
        return this.rawClient.update(allowanceId, request).body();
    }

    /**
     * Updates one or more mutable fields by changing the provider-side mandate first, then committing the same amount, prompt, and expiry locally. Mints are blocked while the update is in flight, and an empty request body is rejected.
     */
    public Allowance update(String allowanceId, AllowancesUpdateRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(allowanceId, request, requestOptions).body();
    }

    /**
     * Lists sanitized provider failures for an allowance, including failed verification and credential attempts. Raw provider bodies and card data are never returned.
     */
    public SyncPagingIterable<SharedPaymentProviderError> errors(String allowanceId) {
        return this.rawClient.errors(allowanceId).body();
    }

    /**
     * Lists sanitized provider failures for an allowance, including failed verification and credential attempts. Raw provider bodies and card data are never returned.
     */
    public SyncPagingIterable<SharedPaymentProviderError> errors(String allowanceId, RequestOptions requestOptions) {
        return this.rawClient.errors(allowanceId, requestOptions).body();
    }

    /**
     * Lists sanitized provider failures for an allowance, including failed verification and credential attempts. Raw provider bodies and card data are never returned.
     */
    public SyncPagingIterable<SharedPaymentProviderError> errors(String allowanceId, AllowancesErrorsRequest request) {
        return this.rawClient.errors(allowanceId, request).body();
    }

    /**
     * Lists sanitized provider failures for an allowance, including failed verification and credential attempts. Raw provider bodies and card data are never returned.
     */
    public SyncPagingIterable<SharedPaymentProviderError> errors(
            String allowanceId, AllowancesErrorsRequest request, RequestOptions requestOptions) {
        return this.rawClient.errors(allowanceId, request, requestOptions).body();
    }

    /**
     * Start or continue self-served verification for a rail that requires it. Public and private applications may call this operation with <code>agentic:allowance:verify</code>; browser clients should use a public application key. Visa verification is advanced through explicit ceremony actions. Mastercard managed authentication is finalized with <code>complete</code> after the hosted ceremony; callback delivery is only a browser signal and is not required.
     */
    public AllowanceVerificationResponse verify(String allowanceId, VerifyAllowanceRequest request) {
        return this.rawClient.verify(allowanceId, request).body();
    }

    /**
     * Start or continue self-served verification for a rail that requires it. Public and private applications may call this operation with <code>agentic:allowance:verify</code>; browser clients should use a public application key. Visa verification is advanced through explicit ceremony actions. Mastercard managed authentication is finalized with <code>complete</code> after the hosted ceremony; callback delivery is only a browser signal and is not required.
     */
    public AllowanceVerificationResponse verify(
            String allowanceId, VerifyAllowanceRequest request, RequestOptions requestOptions) {
        return this.rawClient.verify(allowanceId, request, requestOptions).body();
    }

    public RailsClient rails() {
        return this.railsClient.get();
    }

    public CredentialsClient credentials() {
        return this.credentialsClient.get();
    }
}
