/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic.paymentmethods;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.core.Suppliers;
import com.basistheory.core.pagination.SyncPagingIterable;
import com.basistheory.resources.agentic.paymentmethods.rails.AsyncRailsClient;
import com.basistheory.resources.agentic.paymentmethods.requests.CreatePaymentMethodRequest;
import com.basistheory.resources.agentic.paymentmethods.requests.PaymentMethodsErrorsRequest;
import com.basistheory.resources.agentic.paymentmethods.requests.PaymentMethodsListRequest;
import com.basistheory.types.PaymentMethod;
import com.basistheory.types.SharedPaymentProviderError;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncPaymentMethodsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawPaymentMethodsClient rawClient;

    protected final Supplier<AsyncRailsClient> railsClient;

    public AsyncPaymentMethodsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawPaymentMethodsClient(clientOptions);
        this.railsClient = Suppliers.memoize(() -> new AsyncRailsClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawPaymentMethodsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Lists shared payment methods for the current tenant. Defaults to active resources; use <code>status=all</code> for a complete Portal history. Server-side page filling prevents sparse pages when filtering by status.
     */
    public CompletableFuture<SyncPagingIterable<PaymentMethod>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Lists shared payment methods for the current tenant. Defaults to active resources; use <code>status=all</code> for a complete Portal history. Server-side page filling prevents sparse pages when filtering by status.
     */
    public CompletableFuture<SyncPagingIterable<PaymentMethod>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Lists shared payment methods for the current tenant. Defaults to active resources; use <code>status=all</code> for a complete Portal history. Server-side page filling prevents sparse pages when filtering by status.
     */
    public CompletableFuture<SyncPagingIterable<PaymentMethod>> list(PaymentMethodsListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Lists shared payment methods for the current tenant. Defaults to active resources; use <code>status=all</code> for a complete Portal history. Server-side page filling prevents sparse pages when filtering by status.
     */
    public CompletableFuture<SyncPagingIterable<PaymentMethod>> list(
            PaymentMethodsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Create a shared payment method from a funding source — a Basis Theory card token, or an instrument reached through a source connection — and provision the rails that source is eligible for. Public and private applications may call this operation with <code>agentic:payment-method:create</code>. Supply BT-IDEMPOTENCY-KEY to make matching retries return the same resource. Without it, every request is a new create operation.
     */
    public CompletableFuture<PaymentMethod> create(CreatePaymentMethodRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Create a shared payment method from a funding source — a Basis Theory card token, or an instrument reached through a source connection — and provision the rails that source is eligible for. Public and private applications may call this operation with <code>agentic:payment-method:create</code>. Supply BT-IDEMPOTENCY-KEY to make matching retries return the same resource. Without it, every request is a new create operation.
     */
    public CompletableFuture<PaymentMethod> create(CreatePaymentMethodRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<PaymentMethod> get(String paymentMethodId) {
        return this.rawClient.get(paymentMethodId).thenApply(response -> response.body());
    }

    public CompletableFuture<PaymentMethod> get(String paymentMethodId, RequestOptions requestOptions) {
        return this.rawClient.get(paymentMethodId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Delete a payment method and revoke everything downstream - every allowance backed by it is cancelled (including network-side purchase instructions) and no further verification or credential minting is possible.
     */
    public CompletableFuture<Void> delete(String paymentMethodId) {
        return this.rawClient.delete(paymentMethodId).thenApply(response -> response.body());
    }

    /**
     * Delete a payment method and revoke everything downstream - every allowance backed by it is cancelled (including network-side purchase instructions) and no further verification or credential minting is possible.
     */
    public CompletableFuture<Void> delete(String paymentMethodId, RequestOptions requestOptions) {
        return this.rawClient.delete(paymentMethodId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Lists sanitized provider failures for a payment method and its downstream operations. Raw provider bodies and card data are never returned.
     */
    public CompletableFuture<SyncPagingIterable<SharedPaymentProviderError>> errors(String paymentMethodId) {
        return this.rawClient.errors(paymentMethodId).thenApply(response -> response.body());
    }

    /**
     * Lists sanitized provider failures for a payment method and its downstream operations. Raw provider bodies and card data are never returned.
     */
    public CompletableFuture<SyncPagingIterable<SharedPaymentProviderError>> errors(
            String paymentMethodId, RequestOptions requestOptions) {
        return this.rawClient.errors(paymentMethodId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Lists sanitized provider failures for a payment method and its downstream operations. Raw provider bodies and card data are never returned.
     */
    public CompletableFuture<SyncPagingIterable<SharedPaymentProviderError>> errors(
            String paymentMethodId, PaymentMethodsErrorsRequest request) {
        return this.rawClient.errors(paymentMethodId, request).thenApply(response -> response.body());
    }

    /**
     * Lists sanitized provider failures for a payment method and its downstream operations. Raw provider bodies and card data are never returned.
     */
    public CompletableFuture<SyncPagingIterable<SharedPaymentProviderError>> errors(
            String paymentMethodId, PaymentMethodsErrorsRequest request, RequestOptions requestOptions) {
        return this.rawClient.errors(paymentMethodId, request, requestOptions).thenApply(response -> response.body());
    }

    public AsyncRailsClient rails() {
        return this.railsClient.get();
    }
}
