/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic.paymentmethods;

import com.basistheory.core.BasisTheoryApiApiException;
import com.basistheory.core.BasisTheoryApiHttpResponse;
import com.basistheory.core.BasisTheoryException;
import com.basistheory.core.ClientOptions;
import com.basistheory.core.MediaTypes;
import com.basistheory.core.ObjectMappers;
import com.basistheory.core.QueryStringMapper;
import com.basistheory.core.RequestOptions;
import com.basistheory.core.pagination.SyncPagingIterable;
import com.basistheory.errors.BadRequestError;
import com.basistheory.errors.ConflictError;
import com.basistheory.errors.ForbiddenError;
import com.basistheory.errors.InternalServerError;
import com.basistheory.errors.NotFoundError;
import com.basistheory.errors.NotImplementedError;
import com.basistheory.errors.UnauthorizedError;
import com.basistheory.resources.agentic.paymentmethods.requests.CreatePaymentMethodRequest;
import com.basistheory.resources.agentic.paymentmethods.requests.PaymentMethodsErrorsRequest;
import com.basistheory.resources.agentic.paymentmethods.requests.PaymentMethodsListRequest;
import com.basistheory.types.PaymentMethod;
import com.basistheory.types.PaymentMethodList;
import com.basistheory.types.ProblemDetails;
import com.basistheory.types.SharedPaymentProviderError;
import com.basistheory.types.SharedPaymentProviderErrorList;
import com.basistheory.types.SharedPaymentProviderErrorListPagination;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawPaymentMethodsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawPaymentMethodsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Lists shared payment methods for the current tenant. Defaults to active resources; use <code>status=all</code> for a complete Portal history. Server-side page filling prevents sparse pages when filtering by status.
     */
    public CompletableFuture<BasisTheoryApiHttpResponse<SyncPagingIterable<PaymentMethod>>> list() {
        return list(PaymentMethodsListRequest.builder().build());
    }

    /**
     * Lists shared payment methods for the current tenant. Defaults to active resources; use <code>status=all</code> for a complete Portal history. Server-side page filling prevents sparse pages when filtering by status.
     */
    public CompletableFuture<BasisTheoryApiHttpResponse<SyncPagingIterable<PaymentMethod>>> list(
            RequestOptions requestOptions) {
        return list(PaymentMethodsListRequest.builder().build(), requestOptions);
    }

    /**
     * Lists shared payment methods for the current tenant. Defaults to active resources; use <code>status=all</code> for a complete Portal history. Server-side page filling prevents sparse pages when filtering by status.
     */
    public CompletableFuture<BasisTheoryApiHttpResponse<SyncPagingIterable<PaymentMethod>>> list(
            PaymentMethodsListRequest request) {
        return list(request, null);
    }

    /**
     * Lists shared payment methods for the current tenant. Defaults to active resources; use <code>status=all</code> for a complete Portal history. Server-side page filling prevents sparse pages when filtering by status.
     */
    public CompletableFuture<BasisTheoryApiHttpResponse<SyncPagingIterable<PaymentMethod>>> list(
            PaymentMethodsListRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("agentic/payment-methods");
        if (request.getSize().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "size", request.getSize().get(), false);
        }
        if (request.getStart().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "start", request.getStart().get(), false);
        }
        if (request.getConsumerId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "consumer_id", request.getConsumerId().get(), false);
        }
        if (request.getStatus().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "status", request.getStatus().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<BasisTheoryApiHttpResponse<SyncPagingIterable<PaymentMethod>>> future =
                new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        PaymentMethodList parsedResponse =
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaymentMethodList.class);
                        Optional<String> startingAfter =
                                parsedResponse.getPagination().getNext();
                        PaymentMethodsListRequest nextRequest = PaymentMethodsListRequest.builder()
                                .from(request)
                                .start(startingAfter)
                                .build();
                        List<PaymentMethod> result = parsedResponse.getData();
                        future.complete(new BasisTheoryApiHttpResponse<>(
                                new SyncPagingIterable<PaymentMethod>(
                                        startingAfter.isPresent(), result, parsedResponse, () -> {
                                            try {
                                                return list(nextRequest, requestOptions)
                                                        .get()
                                                        .body();
                                            } catch (InterruptedException | ExecutionException e) {
                                                throw new RuntimeException(e);
                                            }
                                        }),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new BasisTheoryApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new BasisTheoryException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new BasisTheoryException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Create a shared payment method from a funding source — a Basis Theory card token, or an instrument reached through a source connection — and provision the rails that source is eligible for. Public and private applications may call this operation with <code>agentic:payment-method:create</code>. Supply BT-IDEMPOTENCY-KEY to make matching retries return the same resource. Without it, every request is a new create operation.
     */
    public CompletableFuture<BasisTheoryApiHttpResponse<PaymentMethod>> create(CreatePaymentMethodRequest request) {
        return create(request, null);
    }

    /**
     * Create a shared payment method from a funding source — a Basis Theory card token, or an instrument reached through a source connection — and provision the rails that source is eligible for. Public and private applications may call this operation with <code>agentic:payment-method:create</code>. Supply BT-IDEMPOTENCY-KEY to make matching retries return the same resource. Without it, every request is a new create operation.
     */
    public CompletableFuture<BasisTheoryApiHttpResponse<PaymentMethod>> create(
            CreatePaymentMethodRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("agentic/payment-methods");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        if (request.getBtIdempotencyKey().isPresent()) {
            _requestBuilder.addHeader(
                    "BT-IDEMPOTENCY-KEY", request.getBtIdempotencyKey().get());
        }
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<BasisTheoryApiHttpResponse<PaymentMethod>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new BasisTheoryApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaymentMethod.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 501:
                                future.completeExceptionally(new NotImplementedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ProblemDetails.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new BasisTheoryApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new BasisTheoryException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new BasisTheoryException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<BasisTheoryApiHttpResponse<PaymentMethod>> get(String paymentMethodId) {
        return get(paymentMethodId, null);
    }

    public CompletableFuture<BasisTheoryApiHttpResponse<PaymentMethod>> get(
            String paymentMethodId, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("agentic/payment-methods")
                .addPathSegment(paymentMethodId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<BasisTheoryApiHttpResponse<PaymentMethod>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new BasisTheoryApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaymentMethod.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new BasisTheoryApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new BasisTheoryException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new BasisTheoryException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Delete a payment method and revoke everything downstream - every allowance backed by it is cancelled (including network-side purchase instructions) and no further verification or credential minting is possible.
     */
    public CompletableFuture<BasisTheoryApiHttpResponse<Void>> delete(String paymentMethodId) {
        return delete(paymentMethodId, null);
    }

    /**
     * Delete a payment method and revoke everything downstream - every allowance backed by it is cancelled (including network-side purchase instructions) and no further verification or credential minting is possible.
     */
    public CompletableFuture<BasisTheoryApiHttpResponse<Void>> delete(
            String paymentMethodId, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("agentic/payment-methods")
                .addPathSegment(paymentMethodId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<BasisTheoryApiHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new BasisTheoryApiHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new BasisTheoryApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new BasisTheoryException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new BasisTheoryException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Lists sanitized provider failures for a payment method and its downstream operations. Raw provider bodies and card data are never returned.
     */
    public CompletableFuture<BasisTheoryApiHttpResponse<SyncPagingIterable<SharedPaymentProviderError>>> errors(
            String paymentMethodId) {
        return errors(paymentMethodId, PaymentMethodsErrorsRequest.builder().build());
    }

    /**
     * Lists sanitized provider failures for a payment method and its downstream operations. Raw provider bodies and card data are never returned.
     */
    public CompletableFuture<BasisTheoryApiHttpResponse<SyncPagingIterable<SharedPaymentProviderError>>> errors(
            String paymentMethodId, RequestOptions requestOptions) {
        return errors(paymentMethodId, PaymentMethodsErrorsRequest.builder().build(), requestOptions);
    }

    /**
     * Lists sanitized provider failures for a payment method and its downstream operations. Raw provider bodies and card data are never returned.
     */
    public CompletableFuture<BasisTheoryApiHttpResponse<SyncPagingIterable<SharedPaymentProviderError>>> errors(
            String paymentMethodId, PaymentMethodsErrorsRequest request) {
        return errors(paymentMethodId, request, null);
    }

    /**
     * Lists sanitized provider failures for a payment method and its downstream operations. Raw provider bodies and card data are never returned.
     */
    public CompletableFuture<BasisTheoryApiHttpResponse<SyncPagingIterable<SharedPaymentProviderError>>> errors(
            String paymentMethodId, PaymentMethodsErrorsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("agentic/payment-methods")
                .addPathSegment(paymentMethodId)
                .addPathSegments("errors");
        if (request.getSize().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "size", request.getSize().get(), false);
        }
        if (request.getStart().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "start", request.getStart().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<BasisTheoryApiHttpResponse<SyncPagingIterable<SharedPaymentProviderError>>> future =
                new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        SharedPaymentProviderErrorList parsedResponse = ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, SharedPaymentProviderErrorList.class);
                        Optional<String> startingAfter = parsedResponse
                                .getPagination()
                                .flatMap(SharedPaymentProviderErrorListPagination::getNext);
                        PaymentMethodsErrorsRequest nextRequest = PaymentMethodsErrorsRequest.builder()
                                .from(request)
                                .start(startingAfter)
                                .build();
                        List<SharedPaymentProviderError> result =
                                parsedResponse.getData().orElse(Collections.emptyList());
                        future.complete(new BasisTheoryApiHttpResponse<>(
                                new SyncPagingIterable<SharedPaymentProviderError>(
                                        startingAfter.isPresent(), result, parsedResponse, () -> {
                                            try {
                                                return errors(paymentMethodId, nextRequest, requestOptions)
                                                        .get()
                                                        .body();
                                            } catch (InterruptedException | ExecutionException e) {
                                                throw new RuntimeException(e);
                                            }
                                        }),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new BasisTheoryApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new BasisTheoryException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new BasisTheoryException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
