/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic.allowances.credentials;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.core.pagination.SyncPagingIterable;
import com.basistheory.resources.agentic.allowances.credentials.requests.CreatePaymentCredentialRequest;
import com.basistheory.resources.agentic.allowances.credentials.requests.CredentialsListRequest;
import com.basistheory.types.PaymentCredential;
import com.basistheory.types.PaymentCredentialMetadata;
import java.util.concurrent.CompletableFuture;

public class AsyncCredentialsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawCredentialsClient rawClient;

    public AsyncCredentialsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawCredentialsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawCredentialsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List credential metadata for an allowance. Responses contain metadata only — never card numbers, SPT values, or MPP payloads.
     */
    public CompletableFuture<SyncPagingIterable<PaymentCredentialMetadata>> list(String allowanceId) {
        return this.rawClient.list(allowanceId).thenApply(response -> response.body());
    }

    /**
     * List credential metadata for an allowance. Responses contain metadata only — never card numbers, SPT values, or MPP payloads.
     */
    public CompletableFuture<SyncPagingIterable<PaymentCredentialMetadata>> list(
            String allowanceId, RequestOptions requestOptions) {
        return this.rawClient.list(allowanceId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * List credential metadata for an allowance. Responses contain metadata only — never card numbers, SPT values, or MPP payloads.
     */
    public CompletableFuture<SyncPagingIterable<PaymentCredentialMetadata>> list(
            String allowanceId, CredentialsListRequest request) {
        return this.rawClient.list(allowanceId, request).thenApply(response -> response.body());
    }

    /**
     * List credential metadata for an allowance. Responses contain metadata only — never card numbers, SPT values, or MPP payloads.
     */
    public CompletableFuture<SyncPagingIterable<PaymentCredentialMetadata>> list(
            String allowanceId, CredentialsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(allowanceId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Create a spend credential from an allowance. Supply BT-IDEMPOTENCY-KEY for retry protection. Without it, every request is a new mint and may spend the allowance again.
     */
    public CompletableFuture<PaymentCredential> create(String allowanceId, CreatePaymentCredentialRequest request) {
        return this.rawClient.create(allowanceId, request).thenApply(response -> response.body());
    }

    /**
     * Create a spend credential from an allowance. Supply BT-IDEMPOTENCY-KEY for retry protection. Without it, every request is a new mint and may spend the allowance again.
     */
    public CompletableFuture<PaymentCredential> create(
            String allowanceId, CreatePaymentCredentialRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(allowanceId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get credential metadata. The credential payload itself (card number, SPT, MPP token) is only ever returned by the create call.
     */
    public CompletableFuture<PaymentCredentialMetadata> get(String allowanceId, String credentialId) {
        return this.rawClient.get(allowanceId, credentialId).thenApply(response -> response.body());
    }

    /**
     * Get credential metadata. The credential payload itself (card number, SPT, MPP token) is only ever returned by the create call.
     */
    public CompletableFuture<PaymentCredentialMetadata> get(
            String allowanceId, String credentialId, RequestOptions requestOptions) {
        return this.rawClient.get(allowanceId, credentialId, requestOptions).thenApply(response -> response.body());
    }
}
