/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.documents;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.core.Suppliers;
import com.basistheory.resources.documents.data.AsyncDataClient;
import com.basistheory.resources.documents.requests.DocumentsUploadRequest;
import com.basistheory.types.Document;
import java.io.File;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncDocumentsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawDocumentsClient rawClient;

    protected final Supplier<AsyncDataClient> dataClient;

    public AsyncDocumentsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawDocumentsClient(clientOptions);
        this.dataClient = Suppliers.memoize(() -> new AsyncDataClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawDocumentsClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<Document> upload(Optional<File> document) {
        return this.rawClient.upload(document).thenApply(response -> response.body());
    }

    public CompletableFuture<Document> upload(Optional<File> document, DocumentsUploadRequest request) {
        return this.rawClient.upload(document, request).thenApply(response -> response.body());
    }

    public CompletableFuture<Document> upload(
            Optional<File> document, DocumentsUploadRequest request, RequestOptions requestOptions) {
        return this.rawClient.upload(document, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Document> get(String id) {
        return this.rawClient.get(id).thenApply(response -> response.body());
    }

    public CompletableFuture<Document> get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> delete(String id) {
        return this.rawClient.delete(id).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> delete(String id, RequestOptions requestOptions) {
        return this.rawClient.delete(id, requestOptions).thenApply(response -> response.body());
    }

    public AsyncDataClient data() {
        return this.dataClient.get();
    }
}
