/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic.paymentmethods.rails;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.resources.agentic.paymentmethods.rails.requests.RailsRetryRequest;
import com.basistheory.types.PaymentMethod;
import java.util.concurrent.CompletableFuture;

public class AsyncRailsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawRailsClient rawClient;

    public AsyncRailsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawRailsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawRailsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retry one payment method rail after pending or failed provisioning. Public and private applications may call this operation with <code>agentic:payment-method:create</code>.
     */
    public CompletableFuture<PaymentMethod> retry(String paymentMethodId, RailsRetryRequest request) {
        return this.rawClient.retry(paymentMethodId, request).thenApply(response -> response.body());
    }

    /**
     * Retry one payment method rail after pending or failed provisioning. Public and private applications may call this operation with <code>agentic:payment-method:create</code>.
     */
    public CompletableFuture<PaymentMethod> retry(
            String paymentMethodId, RailsRetryRequest request, RequestOptions requestOptions) {
        return this.rawClient.retry(paymentMethodId, request, requestOptions).thenApply(response -> response.body());
    }
}
