/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.accountupdater.realtime;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.resources.accountupdater.realtime.requests.AccountUpdaterRealTimeRequest;
import com.basistheory.types.AccountUpdaterRealTimeResponse;

public class RealTimeClient {
    protected final ClientOptions clientOptions;

    private final RawRealTimeClient rawClient;

    public RealTimeClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawRealTimeClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawRealTimeClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns the update result
     */
    public AccountUpdaterRealTimeResponse invoke(AccountUpdaterRealTimeRequest request) {
        return this.rawClient.invoke(request).body();
    }

    /**
     * Returns the update result
     */
    public AccountUpdaterRealTimeResponse invoke(AccountUpdaterRealTimeRequest request, RequestOptions requestOptions) {
        return this.rawClient.invoke(request, requestOptions).body();
    }
}
