/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic.enrollments.requests;

import com.basistheory.core.ObjectMappers;
import com.basistheory.types.Consumer;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateEnrollmentRequest.Builder.class)
public final class CreateEnrollmentRequest {
    private final String tokenId;

    private final Consumer consumer;

    private final Optional<String> agentId;

    private final Optional<List<String>> agentIds;

    private final Map<String, Object> additionalProperties;

    private CreateEnrollmentRequest(
            String tokenId,
            Consumer consumer,
            Optional<String> agentId,
            Optional<List<String>> agentIds,
            Map<String, Object> additionalProperties) {
        this.tokenId = tokenId;
        this.consumer = consumer;
        this.agentId = agentId;
        this.agentIds = agentIds;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("token_id")
    public String getTokenId() {
        return tokenId;
    }

    @JsonProperty("consumer")
    public Consumer getConsumer() {
        return consumer;
    }

    /**
     * @return Single agent ID (mutually exclusive with agent_ids)
     */
    @JsonProperty("agent_id")
    public Optional<String> getAgentId() {
        return agentId;
    }

    /**
     * @return Multiple agent IDs (mutually exclusive with agent_id)
     */
    @JsonProperty("agent_ids")
    public Optional<List<String>> getAgentIds() {
        return agentIds;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateEnrollmentRequest && equalTo((CreateEnrollmentRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateEnrollmentRequest other) {
        return tokenId.equals(other.tokenId)
                && consumer.equals(other.consumer)
                && agentId.equals(other.agentId)
                && agentIds.equals(other.agentIds);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.tokenId, this.consumer, this.agentId, this.agentIds);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TokenIdStage builder() {
        return new Builder();
    }

    public interface TokenIdStage {
        ConsumerStage tokenId(@NotNull String tokenId);

        Builder from(CreateEnrollmentRequest other);
    }

    public interface ConsumerStage {
        _FinalStage consumer(@NotNull Consumer consumer);
    }

    public interface _FinalStage {
        CreateEnrollmentRequest build();

        /**
         * <p>Single agent ID (mutually exclusive with agent_ids)</p>
         */
        _FinalStage agentId(Optional<String> agentId);

        _FinalStage agentId(String agentId);

        /**
         * <p>Multiple agent IDs (mutually exclusive with agent_id)</p>
         */
        _FinalStage agentIds(Optional<List<String>> agentIds);

        _FinalStage agentIds(List<String> agentIds);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TokenIdStage, ConsumerStage, _FinalStage {
        private String tokenId;

        private Consumer consumer;

        private Optional<List<String>> agentIds = Optional.empty();

        private Optional<String> agentId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateEnrollmentRequest other) {
            tokenId(other.getTokenId());
            consumer(other.getConsumer());
            agentId(other.getAgentId());
            agentIds(other.getAgentIds());
            return this;
        }

        @java.lang.Override
        @JsonSetter("token_id")
        public ConsumerStage tokenId(@NotNull String tokenId) {
            this.tokenId = Objects.requireNonNull(tokenId, "tokenId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("consumer")
        public _FinalStage consumer(@NotNull Consumer consumer) {
            this.consumer = Objects.requireNonNull(consumer, "consumer must not be null");
            return this;
        }

        /**
         * <p>Multiple agent IDs (mutually exclusive with agent_id)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage agentIds(List<String> agentIds) {
            this.agentIds = Optional.ofNullable(agentIds);
            return this;
        }

        /**
         * <p>Multiple agent IDs (mutually exclusive with agent_id)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "agent_ids", nulls = Nulls.SKIP)
        public _FinalStage agentIds(Optional<List<String>> agentIds) {
            this.agentIds = agentIds;
            return this;
        }

        /**
         * <p>Single agent ID (mutually exclusive with agent_ids)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage agentId(String agentId) {
            this.agentId = Optional.ofNullable(agentId);
            return this;
        }

        /**
         * <p>Single agent ID (mutually exclusive with agent_ids)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "agent_id", nulls = Nulls.SKIP)
        public _FinalStage agentId(Optional<String> agentId) {
            this.agentId = agentId;
            return this;
        }

        @java.lang.Override
        public CreateEnrollmentRequest build() {
            return new CreateEnrollmentRequest(tokenId, consumer, agentId, agentIds, additionalProperties);
        }
    }
}
