/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.applepay.merchant.certificates.requests;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ApplePayMerchantCertificatesRegisterRequest.Builder.class)
public final class ApplePayMerchantCertificatesRegisterRequest {
    private final Optional<String> merchantCertificateData;

    private final Optional<String> merchantCertificatePassword;

    private final Optional<String> paymentProcessorCertificateData;

    private final Optional<String> paymentProcessorCertificatePassword;

    private final Optional<String> domain;

    private final Map<String, Object> additionalProperties;

    private ApplePayMerchantCertificatesRegisterRequest(
            Optional<String> merchantCertificateData,
            Optional<String> merchantCertificatePassword,
            Optional<String> paymentProcessorCertificateData,
            Optional<String> paymentProcessorCertificatePassword,
            Optional<String> domain,
            Map<String, Object> additionalProperties) {
        this.merchantCertificateData = merchantCertificateData;
        this.merchantCertificatePassword = merchantCertificatePassword;
        this.paymentProcessorCertificateData = paymentProcessorCertificateData;
        this.paymentProcessorCertificatePassword = paymentProcessorCertificatePassword;
        this.domain = domain;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("merchant_certificate_data")
    public Optional<String> getMerchantCertificateData() {
        return merchantCertificateData;
    }

    @JsonProperty("merchant_certificate_password")
    public Optional<String> getMerchantCertificatePassword() {
        return merchantCertificatePassword;
    }

    @JsonProperty("payment_processor_certificate_data")
    public Optional<String> getPaymentProcessorCertificateData() {
        return paymentProcessorCertificateData;
    }

    @JsonProperty("payment_processor_certificate_password")
    public Optional<String> getPaymentProcessorCertificatePassword() {
        return paymentProcessorCertificatePassword;
    }

    @JsonProperty("domain")
    public Optional<String> getDomain() {
        return domain;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ApplePayMerchantCertificatesRegisterRequest
                && equalTo((ApplePayMerchantCertificatesRegisterRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ApplePayMerchantCertificatesRegisterRequest other) {
        return merchantCertificateData.equals(other.merchantCertificateData)
                && merchantCertificatePassword.equals(other.merchantCertificatePassword)
                && paymentProcessorCertificateData.equals(other.paymentProcessorCertificateData)
                && paymentProcessorCertificatePassword.equals(other.paymentProcessorCertificatePassword)
                && domain.equals(other.domain);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.merchantCertificateData,
                this.merchantCertificatePassword,
                this.paymentProcessorCertificateData,
                this.paymentProcessorCertificatePassword,
                this.domain);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> merchantCertificateData = Optional.empty();

        private Optional<String> merchantCertificatePassword = Optional.empty();

        private Optional<String> paymentProcessorCertificateData = Optional.empty();

        private Optional<String> paymentProcessorCertificatePassword = Optional.empty();

        private Optional<String> domain = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ApplePayMerchantCertificatesRegisterRequest other) {
            merchantCertificateData(other.getMerchantCertificateData());
            merchantCertificatePassword(other.getMerchantCertificatePassword());
            paymentProcessorCertificateData(other.getPaymentProcessorCertificateData());
            paymentProcessorCertificatePassword(other.getPaymentProcessorCertificatePassword());
            domain(other.getDomain());
            return this;
        }

        @JsonSetter(value = "merchant_certificate_data", nulls = Nulls.SKIP)
        public Builder merchantCertificateData(Optional<String> merchantCertificateData) {
            this.merchantCertificateData = merchantCertificateData;
            return this;
        }

        public Builder merchantCertificateData(String merchantCertificateData) {
            this.merchantCertificateData = Optional.ofNullable(merchantCertificateData);
            return this;
        }

        @JsonSetter(value = "merchant_certificate_password", nulls = Nulls.SKIP)
        public Builder merchantCertificatePassword(Optional<String> merchantCertificatePassword) {
            this.merchantCertificatePassword = merchantCertificatePassword;
            return this;
        }

        public Builder merchantCertificatePassword(String merchantCertificatePassword) {
            this.merchantCertificatePassword = Optional.ofNullable(merchantCertificatePassword);
            return this;
        }

        @JsonSetter(value = "payment_processor_certificate_data", nulls = Nulls.SKIP)
        public Builder paymentProcessorCertificateData(Optional<String> paymentProcessorCertificateData) {
            this.paymentProcessorCertificateData = paymentProcessorCertificateData;
            return this;
        }

        public Builder paymentProcessorCertificateData(String paymentProcessorCertificateData) {
            this.paymentProcessorCertificateData = Optional.ofNullable(paymentProcessorCertificateData);
            return this;
        }

        @JsonSetter(value = "payment_processor_certificate_password", nulls = Nulls.SKIP)
        public Builder paymentProcessorCertificatePassword(Optional<String> paymentProcessorCertificatePassword) {
            this.paymentProcessorCertificatePassword = paymentProcessorCertificatePassword;
            return this;
        }

        public Builder paymentProcessorCertificatePassword(String paymentProcessorCertificatePassword) {
            this.paymentProcessorCertificatePassword = Optional.ofNullable(paymentProcessorCertificatePassword);
            return this;
        }

        @JsonSetter(value = "domain", nulls = Nulls.SKIP)
        public Builder domain(Optional<String> domain) {
            this.domain = domain;
            return this;
        }

        public Builder domain(String domain) {
            this.domain = Optional.ofNullable(domain);
            return this;
        }

        public ApplePayMerchantCertificatesRegisterRequest build() {
            return new ApplePayMerchantCertificatesRegisterRequest(
                    merchantCertificateData,
                    merchantCertificatePassword,
                    paymentProcessorCertificateData,
                    paymentProcessorCertificatePassword,
                    domain,
                    additionalProperties);
        }
    }
}
