/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.document.requests;

import com.basistheory.core.ObjectMappers;
import com.basistheory.types.CreateDocumentRequest;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocumentUploadRequest.Builder.class)
public final class DocumentUploadRequest {
    private final Optional<CreateDocumentRequest> request;

    private final Map<String, Object> additionalProperties;

    private DocumentUploadRequest(Optional<CreateDocumentRequest> request, Map<String, Object> additionalProperties) {
        this.request = request;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("request")
    public Optional<CreateDocumentRequest> getRequest() {
        return request;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DocumentUploadRequest && equalTo((DocumentUploadRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DocumentUploadRequest other) {
        return request.equals(other.request);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.request);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<CreateDocumentRequest> request = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DocumentUploadRequest other) {
            request(other.getRequest());
            return this;
        }

        @JsonSetter(value = "request", nulls = Nulls.SKIP)
        public Builder request(Optional<CreateDocumentRequest> request) {
            this.request = request;
            return this;
        }

        public Builder request(CreateDocumentRequest request) {
            this.request = Optional.ofNullable(request);
            return this;
        }

        public DocumentUploadRequest build() {
            return new DocumentUploadRequest(request, additionalProperties);
        }
    }
}
