/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.applicationtemplates;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.types.ApplicationTemplate;
import java.util.List;

public class ApplicationTemplatesClient {
    protected final ClientOptions clientOptions;

    private final RawApplicationTemplatesClient rawClient;

    public ApplicationTemplatesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawApplicationTemplatesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawApplicationTemplatesClient withRawResponse() {
        return this.rawClient;
    }

    public List<ApplicationTemplate> list() {
        return this.rawClient.list().body();
    }

    public List<ApplicationTemplate> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    public ApplicationTemplate get(String id) {
        return this.rawClient.get(id).body();
    }

    public ApplicationTemplate get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).body();
    }
}
