/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.networktokens;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.resources.networktokens.requests.CreateNetworkTokenRequest;
import com.basistheory.types.NetworkToken;
import com.basistheory.types.NetworkTokenCryptogram;

public class NetworkTokensClient {
    protected final ClientOptions clientOptions;

    private final RawNetworkTokensClient rawClient;

    public NetworkTokensClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawNetworkTokensClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawNetworkTokensClient withRawResponse() {
        return this.rawClient;
    }

    public NetworkToken create() {
        return this.rawClient.create().body();
    }

    public NetworkToken create(CreateNetworkTokenRequest request) {
        return this.rawClient.create(request).body();
    }

    public NetworkToken create(CreateNetworkTokenRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    public NetworkTokenCryptogram cryptogram(String id) {
        return this.rawClient.cryptogram(id).body();
    }

    public NetworkTokenCryptogram cryptogram(String id, RequestOptions requestOptions) {
        return this.rawClient.cryptogram(id, requestOptions).body();
    }

    public NetworkToken get(String id) {
        return this.rawClient.get(id).body();
    }

    public NetworkToken get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).body();
    }

    public void delete(String id) {
        this.rawClient.delete(id).body();
    }

    public void delete(String id, RequestOptions requestOptions) {
        this.rawClient.delete(id, requestOptions).body();
    }

    public NetworkToken suspend(String id) {
        return this.rawClient.suspend(id).body();
    }

    public NetworkToken suspend(String id, RequestOptions requestOptions) {
        return this.rawClient.suspend(id, requestOptions).body();
    }

    public NetworkToken resume(String id) {
        return this.rawClient.resume(id).body();
    }

    public NetworkToken resume(String id, RequestOptions requestOptions) {
        return this.rawClient.resume(id, requestOptions).body();
    }
}
