/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic.allowances.credentials.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

public final class CreatePaymentCredentialRequestCredential {
    private final Value value;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    private CreatePaymentCredentialRequestCredential(Value value) {
        this.value = value;
    }

    public <T> T visit(Visitor<T> visitor) {
        return value.visit(visitor);
    }

    public static CreatePaymentCredentialRequestCredential card(CreatePaymentCredentialRequestCredentialCard value) {
        return new CreatePaymentCredentialRequestCredential(new CardValue(value));
    }

    public static CreatePaymentCredentialRequestCredential identifier(
            CreatePaymentCredentialRequestCredentialIdentifier value) {
        return new CreatePaymentCredentialRequestCredential(new IdentifierValue(value));
    }

    public static CreatePaymentCredentialRequestCredential networkToken(
            CreatePaymentCredentialRequestCredentialNetworkToken value) {
        return new CreatePaymentCredentialRequestCredential(new NetworkTokenValue(value));
    }

    public static CreatePaymentCredentialRequestCredential mpp(CreatePaymentCredentialRequestCredentialMpp value) {
        return new CreatePaymentCredentialRequestCredential(new MppValue(value));
    }

    public boolean isCard() {
        return value instanceof CardValue;
    }

    public boolean isIdentifier() {
        return value instanceof IdentifierValue;
    }

    public boolean isNetworkToken() {
        return value instanceof NetworkTokenValue;
    }

    public boolean isMpp() {
        return value instanceof MppValue;
    }

    public boolean _isUnknown() {
        return value instanceof _UnknownValue;
    }

    public Optional<CreatePaymentCredentialRequestCredentialCard> getCard() {
        if (isCard()) {
            return Optional.of(((CardValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreatePaymentCredentialRequestCredentialIdentifier> getIdentifier() {
        if (isIdentifier()) {
            return Optional.of(((IdentifierValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreatePaymentCredentialRequestCredentialNetworkToken> getNetworkToken() {
        if (isNetworkToken()) {
            return Optional.of(((NetworkTokenValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<CreatePaymentCredentialRequestCredentialMpp> getMpp() {
        if (isMpp()) {
            return Optional.of(((MppValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> _getUnknown() {
        if (_isUnknown()) {
            return Optional.of(((_UnknownValue) value).value);
        }
        return Optional.empty();
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreatePaymentCredentialRequestCredential
                && value.equals(((CreatePaymentCredentialRequestCredential) other).value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public String toString() {
        return value.toString();
    }

    @JsonValue
    private Value getValue() {
        return this.value;
    }

    public interface Visitor<T> {
        T visitCard(CreatePaymentCredentialRequestCredentialCard card);

        T visitIdentifier(CreatePaymentCredentialRequestCredentialIdentifier identifier);

        T visitNetworkToken(CreatePaymentCredentialRequestCredentialNetworkToken networkToken);

        T visitMpp(CreatePaymentCredentialRequestCredentialMpp mpp);

        T _visitUnknown(Object unknownType);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "format", visible = true, defaultImpl = _UnknownValue.class)
    @JsonSubTypes({
        @JsonSubTypes.Type(CardValue.class),
        @JsonSubTypes.Type(IdentifierValue.class),
        @JsonSubTypes.Type(NetworkTokenValue.class),
        @JsonSubTypes.Type(MppValue.class)
    })
    @JsonIgnoreProperties(ignoreUnknown = true)
    private interface Value {
        <T> T visit(Visitor<T> visitor);
    }

    @JsonTypeName("card")
    @JsonIgnoreProperties("format")
    private static final class CardValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "format", allowSetters = true)
        private CreatePaymentCredentialRequestCredentialCard value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private CardValue() {}

        private CardValue(CreatePaymentCredentialRequestCredentialCard value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitCard(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof CardValue && equalTo((CardValue) other);
        }

        private boolean equalTo(CardValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreatePaymentCredentialRequestCredential{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("identifier")
    @JsonIgnoreProperties("format")
    private static final class IdentifierValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "format", allowSetters = true)
        private CreatePaymentCredentialRequestCredentialIdentifier value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private IdentifierValue() {}

        private IdentifierValue(CreatePaymentCredentialRequestCredentialIdentifier value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitIdentifier(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof IdentifierValue && equalTo((IdentifierValue) other);
        }

        private boolean equalTo(IdentifierValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreatePaymentCredentialRequestCredential{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("network-token")
    @JsonIgnoreProperties("format")
    private static final class NetworkTokenValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "format", allowSetters = true)
        private CreatePaymentCredentialRequestCredentialNetworkToken value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private NetworkTokenValue() {}

        private NetworkTokenValue(CreatePaymentCredentialRequestCredentialNetworkToken value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitNetworkToken(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof NetworkTokenValue && equalTo((NetworkTokenValue) other);
        }

        private boolean equalTo(NetworkTokenValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreatePaymentCredentialRequestCredential{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("mpp")
    @JsonIgnoreProperties("format")
    private static final class MppValue implements Value {
        @JsonUnwrapped
        @JsonIgnoreProperties(value = "format", allowSetters = true)
        private CreatePaymentCredentialRequestCredentialMpp value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private MppValue() {}

        private MppValue(CreatePaymentCredentialRequestCredentialMpp value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitMpp(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof MppValue && equalTo((MppValue) other);
        }

        private boolean equalTo(MppValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreatePaymentCredentialRequestCredential{" + "value: " + value + "}";
        }
    }

    @JsonIgnoreProperties("format")
    private static final class _UnknownValue implements Value {
        private String type;

        @JsonValue
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _UnknownValue(@JsonProperty("value") Object value) {}

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor._visitUnknown(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
        }

        private boolean equalTo(_UnknownValue other) {
            return type.equals(other.type) && value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.type, this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreatePaymentCredentialRequestCredential{" + "type: " + type + ", value: " + value + "}";
        }
    }
}
