/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.events;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.core.pagination.SyncPagingIterable;
import com.basistheory.resources.events.requests.EventsListRequest;
import com.basistheory.types.Event;
import java.util.concurrent.CompletableFuture;

public class AsyncEventsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawEventsClient rawClient;

    public AsyncEventsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawEventsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawEventsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Requires event:read. Tenant identity comes from trusted API-key authentication. History is limited by log_history_limit (24 hours by default, at most 30 days). Windows reaching outside the visible history are clamped to it rather than rejected. No secondary failover or portal JWT support. SDK callers supply data.&lt;path&gt; filters as literal keys through the SDK's per-request query-parameter options, not as a filters request field.
     */
    public CompletableFuture<SyncPagingIterable<Event>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Requires event:read. Tenant identity comes from trusted API-key authentication. History is limited by log_history_limit (24 hours by default, at most 30 days). Windows reaching outside the visible history are clamped to it rather than rejected. No secondary failover or portal JWT support. SDK callers supply data.&lt;path&gt; filters as literal keys through the SDK's per-request query-parameter options, not as a filters request field.
     */
    public CompletableFuture<SyncPagingIterable<Event>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Requires event:read. Tenant identity comes from trusted API-key authentication. History is limited by log_history_limit (24 hours by default, at most 30 days). Windows reaching outside the visible history are clamped to it rather than rejected. No secondary failover or portal JWT support. SDK callers supply data.&lt;path&gt; filters as literal keys through the SDK's per-request query-parameter options, not as a filters request field.
     */
    public CompletableFuture<SyncPagingIterable<Event>> list(EventsListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Requires event:read. Tenant identity comes from trusted API-key authentication. History is limited by log_history_limit (24 hours by default, at most 30 days). Windows reaching outside the visible history are clamped to it rather than rejected. No secondary failover or portal JWT support. SDK callers supply data.&lt;path&gt; filters as literal keys through the SDK's per-request query-parameter options, not as a filters request field.
     */
    public CompletableFuture<SyncPagingIterable<Event>> list(EventsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }
}
