/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic.allowances.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum AllowancesListRequestStatus {
    ACTIVE("active"),

    CANCELLED("cancelled"),

    EXPIRED("expired"),

    ALL("all");

    private final String value;

    AllowancesListRequestStatus(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
