/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.tenants.securitycontact;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.resources.tenants.securitycontact.requests.SecurityContactEmailRequest;
import com.basistheory.types.SecurityContactEmailResponse;

public class SecurityContactClient {
    protected final ClientOptions clientOptions;

    private final RawSecurityContactClient rawClient;

    public SecurityContactClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawSecurityContactClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawSecurityContactClient withRawResponse() {
        return this.rawClient;
    }

    public SecurityContactEmailResponse get() {
        return this.rawClient.get().body();
    }

    public SecurityContactEmailResponse get(RequestOptions requestOptions) {
        return this.rawClient.get(requestOptions).body();
    }

    public SecurityContactEmailResponse update(SecurityContactEmailRequest request) {
        return this.rawClient.update(request).body();
    }

    public SecurityContactEmailResponse update(SecurityContactEmailRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(request, requestOptions).body();
    }
}
