/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.roles;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.types.Role;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncRolesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawRolesClient rawClient;

    public AsyncRolesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawRolesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawRolesClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<List<Role>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    public CompletableFuture<List<Role>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }
}
