/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.Suppliers;
import com.basistheory.resources.agentic.agents.AgentsClient;
import com.basistheory.resources.agentic.enrollments.EnrollmentsClient;
import java.util.function.Supplier;

public class AgenticClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AgentsClient> agentsClient;

    protected final Supplier<EnrollmentsClient> enrollmentsClient;

    public AgenticClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.agentsClient = Suppliers.memoize(() -> new AgentsClient(clientOptions));
        this.enrollmentsClient = Suppliers.memoize(() -> new EnrollmentsClient(clientOptions));
    }

    public AgentsClient agents() {
        return this.agentsClient.get();
    }

    public EnrollmentsClient enrollments() {
        return this.enrollmentsClient.get();
    }
}
