/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basis.theory.api.errors;

import com.basis.theory.api.core.BasisTheoryApiApiException;
import com.basis.theory.api.types.ValidationProblemDetails;

public final class BadRequestError extends BasisTheoryApiApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final ValidationProblemDetails body;

    public BadRequestError(ValidationProblemDetails body) {
        super("BadRequestError", 400, body);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public ValidationProblemDetails body() {
        return this.body;
    }
}
