/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.errors;

import com.basistheory.core.BasisTheoryApiApiException;
import com.basistheory.types.ProblemDetails;
import okhttp3.Response;

public final class NotImplementedError extends BasisTheoryApiApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final ProblemDetails body;

    public NotImplementedError(ProblemDetails body) {
        super("NotImplementedError", 501, body);
        this.body = body;
    }

    public NotImplementedError(ProblemDetails body, Response rawResponse) {
        super("NotImplementedError", 501, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public ProblemDetails body() {
        return this.body;
    }
}
