/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AgenticProblemDetails.Builder.class)
public final class AgenticProblemDetails {
    private final Optional<String> type;

    private final Optional<String> title;

    private final Optional<Integer> status;

    private final Optional<String> detail;

    private final Optional<Map<String, Optional<List<String>>>> errors;

    private final Map<String, Object> additionalProperties;

    private AgenticProblemDetails(
            Optional<String> type,
            Optional<String> title,
            Optional<Integer> status,
            Optional<String> detail,
            Optional<Map<String, Optional<List<String>>>> errors,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.title = title;
        this.status = status;
        this.detail = detail;
        this.errors = errors;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Error code identifier
     */
    @JsonProperty("type")
    public Optional<String> getType() {
        return type;
    }

    /**
     * @return Human-readable error summary
     */
    @JsonProperty("title")
    public Optional<String> getTitle() {
        return title;
    }

    /**
     * @return HTTP status code
     */
    @JsonProperty("status")
    public Optional<Integer> getStatus() {
        return status;
    }

    /**
     * @return Additional context about the error
     */
    @JsonProperty("detail")
    public Optional<String> getDetail() {
        return detail;
    }

    /**
     * @return Field-level validation errors
     */
    @JsonProperty("errors")
    public Optional<Map<String, Optional<List<String>>>> getErrors() {
        return errors;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgenticProblemDetails && equalTo((AgenticProblemDetails) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AgenticProblemDetails other) {
        return type.equals(other.type)
                && title.equals(other.title)
                && status.equals(other.status)
                && detail.equals(other.detail)
                && errors.equals(other.errors);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.title, this.status, this.detail, this.errors);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> type = Optional.empty();

        private Optional<String> title = Optional.empty();

        private Optional<Integer> status = Optional.empty();

        private Optional<String> detail = Optional.empty();

        private Optional<Map<String, Optional<List<String>>>> errors = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(AgenticProblemDetails other) {
            type(other.getType());
            title(other.getTitle());
            status(other.getStatus());
            detail(other.getDetail());
            errors(other.getErrors());
            return this;
        }

        /**
         * <p>Error code identifier</p>
         */
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<String> type) {
            this.type = type;
            return this;
        }

        public Builder type(String type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * <p>Human-readable error summary</p>
         */
        @JsonSetter(value = "title", nulls = Nulls.SKIP)
        public Builder title(Optional<String> title) {
            this.title = title;
            return this;
        }

        public Builder title(String title) {
            this.title = Optional.ofNullable(title);
            return this;
        }

        /**
         * <p>HTTP status code</p>
         */
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<Integer> status) {
            this.status = status;
            return this;
        }

        public Builder status(Integer status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>Additional context about the error</p>
         */
        @JsonSetter(value = "detail", nulls = Nulls.SKIP)
        public Builder detail(Optional<String> detail) {
            this.detail = detail;
            return this;
        }

        public Builder detail(String detail) {
            this.detail = Optional.ofNullable(detail);
            return this;
        }

        /**
         * <p>Field-level validation errors</p>
         */
        @JsonSetter(value = "errors", nulls = Nulls.SKIP)
        public Builder errors(Optional<Map<String, Optional<List<String>>>> errors) {
            this.errors = errors;
            return this;
        }

        public Builder errors(Map<String, Optional<List<String>>> errors) {
            this.errors = Optional.ofNullable(errors);
            return this;
        }

        public AgenticProblemDetails build() {
            return new AgenticProblemDetails(type, title, status, detail, errors, additionalProperties);
        }
    }
}
