/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum AllowanceVerificationMethodType {
    SMS("sms"),

    EMAIL("email"),

    OTPONLINEBANKING("otponlinebanking");

    private final String value;

    AllowanceVerificationMethodType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
