/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum AllowanceStatus {
    ACTIVE("active"),

    CANCELLED("cancelled"),

    EXPIRED("expired");

    private final String value;

    AllowanceStatus(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
