/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConnectionInstrument.Builder.class)
public final class ConnectionInstrument {
    private final String instrumentId;

    private final ConnectionInstrumentType type;

    private final boolean isDefault;

    private final Optional<String> nickname;

    private final Optional<Map<String, Object>> display;

    private final Map<String, Object> additionalProperties;

    private ConnectionInstrument(
            String instrumentId,
            ConnectionInstrumentType type,
            boolean isDefault,
            Optional<String> nickname,
            Optional<Map<String, Object>> display,
            Map<String, Object> additionalProperties) {
        this.instrumentId = instrumentId;
        this.type = type;
        this.isDefault = isDefault;
        this.nickname = nickname;
        this.display = display;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("instrument_id")
    public String getInstrumentId() {
        return instrumentId;
    }

    /**
     * @return <code>other</code> is the mandatory catch-all. An instrument we cannot classify is still listed — dropping it silently would hide a card the consumer can see in their own wallet.
     */
    @JsonProperty("type")
    public ConnectionInstrumentType getType() {
        return type;
    }

    @JsonProperty("is_default")
    public boolean getIsDefault() {
        return isDefault;
    }

    @JsonProperty("nickname")
    public Optional<String> getNickname() {
        return nickname;
    }

    /**
     * @return Non-sensitive identifying data, shaped by <code>type</code>. Empty for <code>other</code>. Never contains a PAN, a CVC, or a key.
     */
    @JsonProperty("display")
    public Optional<Map<String, Object>> getDisplay() {
        return display;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConnectionInstrument && equalTo((ConnectionInstrument) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConnectionInstrument other) {
        return instrumentId.equals(other.instrumentId)
                && type.equals(other.type)
                && isDefault == other.isDefault
                && nickname.equals(other.nickname)
                && display.equals(other.display);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.instrumentId, this.type, this.isDefault, this.nickname, this.display);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static InstrumentIdStage builder() {
        return new Builder();
    }

    public interface InstrumentIdStage {
        TypeStage instrumentId(@NotNull String instrumentId);

        Builder from(ConnectionInstrument other);
    }

    public interface TypeStage {
        /**
         * <p><code>other</code> is the mandatory catch-all. An instrument we cannot classify is still listed — dropping it silently would hide a card the consumer can see in their own wallet.</p>
         */
        IsDefaultStage type(@NotNull ConnectionInstrumentType type);
    }

    public interface IsDefaultStage {
        _FinalStage isDefault(boolean isDefault);
    }

    public interface _FinalStage {
        ConnectionInstrument build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage nickname(Optional<String> nickname);

        _FinalStage nickname(String nickname);

        /**
         * <p>Non-sensitive identifying data, shaped by <code>type</code>. Empty for <code>other</code>. Never contains a PAN, a CVC, or a key.</p>
         */
        _FinalStage display(Optional<Map<String, Object>> display);

        _FinalStage display(Map<String, Object> display);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements InstrumentIdStage, TypeStage, IsDefaultStage, _FinalStage {
        private String instrumentId;

        private ConnectionInstrumentType type;

        private boolean isDefault;

        private Optional<Map<String, Object>> display = Optional.empty();

        private Optional<String> nickname = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ConnectionInstrument other) {
            instrumentId(other.getInstrumentId());
            type(other.getType());
            isDefault(other.getIsDefault());
            nickname(other.getNickname());
            display(other.getDisplay());
            return this;
        }

        @java.lang.Override
        @JsonSetter("instrument_id")
        public TypeStage instrumentId(@NotNull String instrumentId) {
            this.instrumentId = Objects.requireNonNull(instrumentId, "instrumentId must not be null");
            return this;
        }

        /**
         * <p><code>other</code> is the mandatory catch-all. An instrument we cannot classify is still listed — dropping it silently would hide a card the consumer can see in their own wallet.</p>
         * <p><code>other</code> is the mandatory catch-all. An instrument we cannot classify is still listed — dropping it silently would hide a card the consumer can see in their own wallet.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public IsDefaultStage type(@NotNull ConnectionInstrumentType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("is_default")
        public _FinalStage isDefault(boolean isDefault) {
            this.isDefault = isDefault;
            return this;
        }

        /**
         * <p>Non-sensitive identifying data, shaped by <code>type</code>. Empty for <code>other</code>. Never contains a PAN, a CVC, or a key.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage display(Map<String, Object> display) {
            this.display = Optional.ofNullable(display);
            return this;
        }

        /**
         * <p>Non-sensitive identifying data, shaped by <code>type</code>. Empty for <code>other</code>. Never contains a PAN, a CVC, or a key.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "display", nulls = Nulls.SKIP)
        public _FinalStage display(Optional<Map<String, Object>> display) {
            this.display = display;
            return this;
        }

        @java.lang.Override
        public _FinalStage nickname(String nickname) {
            this.nickname = Optional.ofNullable(nickname);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "nickname", nulls = Nulls.SKIP)
        public _FinalStage nickname(Optional<String> nickname) {
            this.nickname = nickname;
            return this;
        }

        @java.lang.Override
        public ConnectionInstrument build() {
            return new ConnectionInstrument(instrumentId, type, isDefault, nickname, display, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
