/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConnectionAuthorizationDetailsItem.Builder.class)
public final class ConnectionAuthorizationDetailsItem {
    private final String type;

    private final List<String> actions;

    private final Map<String, Object> additionalProperties;

    private ConnectionAuthorizationDetailsItem(
            String type, List<String> actions, Map<String, Object> additionalProperties) {
        this.type = type;
        this.actions = actions;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    public String getType() {
        return type;
    }

    @JsonProperty("actions")
    public List<String> getActions() {
        return actions;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConnectionAuthorizationDetailsItem
                && equalTo((ConnectionAuthorizationDetailsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConnectionAuthorizationDetailsItem other) {
        return type.equals(other.type) && actions.equals(other.actions);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.actions);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        _FinalStage type(@NotNull String type);

        Builder from(ConnectionAuthorizationDetailsItem other);
    }

    public interface _FinalStage {
        ConnectionAuthorizationDetailsItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage actions(List<String> actions);

        _FinalStage addActions(String actions);

        _FinalStage addAllActions(List<String> actions);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, _FinalStage {
        private String type;

        private List<String> actions = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ConnectionAuthorizationDetailsItem other) {
            type(other.getType());
            actions(other.getActions());
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull String type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllActions(List<String> actions) {
            if (actions != null) {
                this.actions.addAll(actions);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addActions(String actions) {
            this.actions.add(actions);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "actions", nulls = Nulls.SKIP)
        public _FinalStage actions(List<String> actions) {
            this.actions.clear();
            if (actions != null) {
                this.actions.addAll(actions);
            }
            return this;
        }

        @java.lang.Override
        public ConnectionAuthorizationDetailsItem build() {
            return new ConnectionAuthorizationDetailsItem(type, actions, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
