/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateConnectionRequest.Builder.class)
public final class CreateConnectionRequest {
    private final String provider;

    private final Optional<String> grantMethod;

    private final Optional<ConnectionPrincipal> principal;

    private final Optional<List<String>> permissions;

    private final Map<String, Object> additionalProperties;

    private CreateConnectionRequest(
            String provider,
            Optional<String> grantMethod,
            Optional<ConnectionPrincipal> principal,
            Optional<List<String>> permissions,
            Map<String, Object> additionalProperties) {
        this.provider = provider;
        this.grantMethod = grantMethod;
        this.principal = principal;
        this.permissions = permissions;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("provider")
    public String getProvider() {
        return provider;
    }

    /**
     * @return Omit to use the provider's default grant method.
     */
    @JsonProperty("grant_method")
    public Optional<String> getGrantMethod() {
        return grantMethod;
    }

    @JsonProperty("principal")
    public Optional<ConnectionPrincipal> getPrincipal() {
        return principal;
    }

    /**
     * @return Exact provider-native permission strings to request. Omit to use the grant method's defaults. Validated against the provider's own vocabulary, not against a Basis Theory enum.
     */
    @JsonProperty("permissions")
    public Optional<List<String>> getPermissions() {
        return permissions;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateConnectionRequest && equalTo((CreateConnectionRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateConnectionRequest other) {
        return provider.equals(other.provider)
                && grantMethod.equals(other.grantMethod)
                && principal.equals(other.principal)
                && permissions.equals(other.permissions);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.provider, this.grantMethod, this.principal, this.permissions);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ProviderStage builder() {
        return new Builder();
    }

    public interface ProviderStage {
        _FinalStage provider(@NotNull String provider);

        Builder from(CreateConnectionRequest other);
    }

    public interface _FinalStage {
        CreateConnectionRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Omit to use the provider's default grant method.</p>
         */
        _FinalStage grantMethod(Optional<String> grantMethod);

        _FinalStage grantMethod(String grantMethod);

        _FinalStage principal(Optional<ConnectionPrincipal> principal);

        _FinalStage principal(ConnectionPrincipal principal);

        /**
         * <p>Exact provider-native permission strings to request. Omit to use the grant method's defaults. Validated against the provider's own vocabulary, not against a Basis Theory enum.</p>
         */
        _FinalStage permissions(Optional<List<String>> permissions);

        _FinalStage permissions(List<String> permissions);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ProviderStage, _FinalStage {
        private String provider;

        private Optional<List<String>> permissions = Optional.empty();

        private Optional<ConnectionPrincipal> principal = Optional.empty();

        private Optional<String> grantMethod = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateConnectionRequest other) {
            provider(other.getProvider());
            grantMethod(other.getGrantMethod());
            principal(other.getPrincipal());
            permissions(other.getPermissions());
            return this;
        }

        @java.lang.Override
        @JsonSetter("provider")
        public _FinalStage provider(@NotNull String provider) {
            this.provider = Objects.requireNonNull(provider, "provider must not be null");
            return this;
        }

        /**
         * <p>Exact provider-native permission strings to request. Omit to use the grant method's defaults. Validated against the provider's own vocabulary, not against a Basis Theory enum.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage permissions(List<String> permissions) {
            this.permissions = Optional.ofNullable(permissions);
            return this;
        }

        /**
         * <p>Exact provider-native permission strings to request. Omit to use the grant method's defaults. Validated against the provider's own vocabulary, not against a Basis Theory enum.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "permissions", nulls = Nulls.SKIP)
        public _FinalStage permissions(Optional<List<String>> permissions) {
            this.permissions = permissions;
            return this;
        }

        @java.lang.Override
        public _FinalStage principal(ConnectionPrincipal principal) {
            this.principal = Optional.ofNullable(principal);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "principal", nulls = Nulls.SKIP)
        public _FinalStage principal(Optional<ConnectionPrincipal> principal) {
            this.principal = principal;
            return this;
        }

        /**
         * <p>Omit to use the provider's default grant method.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage grantMethod(String grantMethod) {
            this.grantMethod = Optional.ofNullable(grantMethod);
            return this;
        }

        /**
         * <p>Omit to use the provider's default grant method.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "grant_method", nulls = Nulls.SKIP)
        public _FinalStage grantMethod(Optional<String> grantMethod) {
            this.grantMethod = grantMethod;
            return this;
        }

        @java.lang.Override
        public CreateConnectionRequest build() {
            return new CreateConnectionRequest(provider, grantMethod, principal, permissions, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
