/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateAccountUpdaterJobRequest.Builder.class)
public final class CreateAccountUpdaterJobRequest {
    private final Optional<Boolean> deduplicateTokens;

    private final Map<String, Object> additionalProperties;

    private CreateAccountUpdaterJobRequest(
            Optional<Boolean> deduplicateTokens, Map<String, Object> additionalProperties) {
        this.deduplicateTokens = deduplicateTokens;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Whether deduplication should be enabled when creating new tokens. Uses the value of the Deduplicate Tokens setting on the tenant if not set.
     */
    @JsonProperty("deduplicate_tokens")
    public Optional<Boolean> getDeduplicateTokens() {
        return deduplicateTokens;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateAccountUpdaterJobRequest && equalTo((CreateAccountUpdaterJobRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateAccountUpdaterJobRequest other) {
        return deduplicateTokens.equals(other.deduplicateTokens);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.deduplicateTokens);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> deduplicateTokens = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateAccountUpdaterJobRequest other) {
            deduplicateTokens(other.getDeduplicateTokens());
            return this;
        }

        @JsonSetter(value = "deduplicate_tokens", nulls = Nulls.SKIP)
        public Builder deduplicateTokens(Optional<Boolean> deduplicateTokens) {
            this.deduplicateTokens = deduplicateTokens;
            return this;
        }

        public Builder deduplicateTokens(Boolean deduplicateTokens) {
            this.deduplicateTokens = Optional.ofNullable(deduplicateTokens);
            return this;
        }

        public CreateAccountUpdaterJobRequest build() {
            return new CreateAccountUpdaterJobRequest(deduplicateTokens, additionalProperties);
        }
    }
}
