/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FunctionSourceDetection.Builder.class)
public final class FunctionSourceDetection {
    private final Optional<String> category;

    private final Optional<Integer> start;

    private final Optional<Integer> length;

    private final Map<String, Object> additionalProperties;

    private FunctionSourceDetection(
            Optional<String> category,
            Optional<Integer> start,
            Optional<Integer> length,
            Map<String, Object> additionalProperties) {
        this.category = category;
        this.start = start;
        this.length = length;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("category")
    public Optional<String> getCategory() {
        return category;
    }

    @JsonProperty("start")
    public Optional<Integer> getStart() {
        return start;
    }

    @JsonProperty("length")
    public Optional<Integer> getLength() {
        return length;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FunctionSourceDetection && equalTo((FunctionSourceDetection) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FunctionSourceDetection other) {
        return category.equals(other.category) && start.equals(other.start) && length.equals(other.length);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.category, this.start, this.length);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> category = Optional.empty();

        private Optional<Integer> start = Optional.empty();

        private Optional<Integer> length = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(FunctionSourceDetection other) {
            category(other.getCategory());
            start(other.getStart());
            length(other.getLength());
            return this;
        }

        @JsonSetter(value = "category", nulls = Nulls.SKIP)
        public Builder category(Optional<String> category) {
            this.category = category;
            return this;
        }

        public Builder category(String category) {
            this.category = Optional.ofNullable(category);
            return this;
        }

        @JsonSetter(value = "start", nulls = Nulls.SKIP)
        public Builder start(Optional<Integer> start) {
            this.start = start;
            return this;
        }

        public Builder start(Integer start) {
            this.start = Optional.ofNullable(start);
            return this;
        }

        @JsonSetter(value = "length", nulls = Nulls.SKIP)
        public Builder length(Optional<Integer> length) {
            this.length = length;
            return this;
        }

        public Builder length(Integer length) {
            this.length = Optional.ofNullable(length);
            return this;
        }

        public FunctionSourceDetection build() {
            return new FunctionSourceDetection(category, start, length, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
