/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TokenMetrics.Builder.class)
public final class TokenMetrics {
    private final Optional<Long> count;

    private final Optional<OffsetDateTime> lastCreatedAt;

    private final Map<String, Object> additionalProperties;

    private TokenMetrics(
            Optional<Long> count, Optional<OffsetDateTime> lastCreatedAt, Map<String, Object> additionalProperties) {
        this.count = count;
        this.lastCreatedAt = lastCreatedAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("count")
    public Optional<Long> getCount() {
        return count;
    }

    @JsonProperty("last_created_at")
    public Optional<OffsetDateTime> getLastCreatedAt() {
        return lastCreatedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TokenMetrics && equalTo((TokenMetrics) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TokenMetrics other) {
        return count.equals(other.count) && lastCreatedAt.equals(other.lastCreatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.count, this.lastCreatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Long> count = Optional.empty();

        private Optional<OffsetDateTime> lastCreatedAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TokenMetrics other) {
            count(other.getCount());
            lastCreatedAt(other.getLastCreatedAt());
            return this;
        }

        @JsonSetter(value = "count", nulls = Nulls.SKIP)
        public Builder count(Optional<Long> count) {
            this.count = count;
            return this;
        }

        public Builder count(Long count) {
            this.count = Optional.ofNullable(count);
            return this;
        }

        @JsonSetter(value = "last_created_at", nulls = Nulls.SKIP)
        public Builder lastCreatedAt(Optional<OffsetDateTime> lastCreatedAt) {
            this.lastCreatedAt = lastCreatedAt;
            return this;
        }

        public Builder lastCreatedAt(OffsetDateTime lastCreatedAt) {
            this.lastCreatedAt = Optional.ofNullable(lastCreatedAt);
            return this;
        }

        public TokenMetrics build() {
            return new TokenMetrics(count, lastCreatedAt, additionalProperties);
        }
    }
}
