/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = VerifyAllowanceRequestStartDeviceContext.Builder.class)
public final class VerifyAllowanceRequestStartDeviceContext {
    private final Optional<String> languageCode;

    private final Optional<String> timeZone;

    private final Map<String, Object> additionalProperties;

    private VerifyAllowanceRequestStartDeviceContext(
            Optional<String> languageCode, Optional<String> timeZone, Map<String, Object> additionalProperties) {
        this.languageCode = languageCode;
        this.timeZone = timeZone;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return BCP 47 language tag. Canonicalized on input (for example, <code>EN-us</code> becomes <code>en-US</code>); underscore locales such as <code>en_US</code> are rejected.
     */
    @JsonProperty("language_code")
    public Optional<String> getLanguageCode() {
        return languageCode;
    }

    /**
     * @return IANA time zone identifier, such as <code>America/New_York</code>.
     */
    @JsonProperty("time_zone")
    public Optional<String> getTimeZone() {
        return timeZone;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof VerifyAllowanceRequestStartDeviceContext
                && equalTo((VerifyAllowanceRequestStartDeviceContext) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(VerifyAllowanceRequestStartDeviceContext other) {
        return languageCode.equals(other.languageCode) && timeZone.equals(other.timeZone);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.languageCode, this.timeZone);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> languageCode = Optional.empty();

        private Optional<String> timeZone = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(VerifyAllowanceRequestStartDeviceContext other) {
            languageCode(other.getLanguageCode());
            timeZone(other.getTimeZone());
            return this;
        }

        /**
         * <p>BCP 47 language tag. Canonicalized on input (for example, <code>EN-us</code> becomes <code>en-US</code>); underscore locales such as <code>en_US</code> are rejected.</p>
         */
        @JsonSetter(value = "language_code", nulls = Nulls.SKIP)
        public Builder languageCode(Optional<String> languageCode) {
            this.languageCode = languageCode;
            return this;
        }

        public Builder languageCode(String languageCode) {
            this.languageCode = Optional.ofNullable(languageCode);
            return this;
        }

        /**
         * <p>IANA time zone identifier, such as <code>America/New_York</code>.</p>
         */
        @JsonSetter(value = "time_zone", nulls = Nulls.SKIP)
        public Builder timeZone(Optional<String> timeZone) {
            this.timeZone = timeZone;
            return this;
        }

        public Builder timeZone(String timeZone) {
            this.timeZone = Optional.ofNullable(timeZone);
            return this;
        }

        public VerifyAllowanceRequestStartDeviceContext build() {
            return new VerifyAllowanceRequestStartDeviceContext(languageCode, timeZone, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
