/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.events.requests;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventsListRequest.Builder.class)
public final class EventsListRequest {
    private final Optional<OffsetDateTime> startDate;

    private final Optional<OffsetDateTime> endDate;

    private final Optional<String> start;

    private final Optional<Integer> size;

    private final Optional<String> type;

    private final Optional<String> traceId;

    private final Map<String, Object> additionalProperties;

    private EventsListRequest(
            Optional<OffsetDateTime> startDate,
            Optional<OffsetDateTime> endDate,
            Optional<String> start,
            Optional<Integer> size,
            Optional<String> type,
            Optional<String> traceId,
            Map<String, Object> additionalProperties) {
        this.startDate = startDate;
        this.endDate = endDate;
        this.start = start;
        this.size = size;
        this.type = type;
        this.traceId = traceId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Inclusive timestamp; defaults to 24 hours before end_date, shortened to tenant entitlement. An earlier value is raised to the oldest visible instant. ISO 8601 with timezone, at most millisecond precision. Must not be after end_date.
     */
    @JsonProperty("start_date")
    public Optional<OffsetDateTime> getStartDate() {
        return startDate;
    }

    /**
     * @return Exclusive timestamp; defaults to request time. A future value is lowered to request time. A window with no visible history returns an empty page.
     */
    @JsonProperty("end_date")
    public Optional<OffsetDateTime> getEndDate() {
        return endDate;
    }

    /**
     * @return Opaque cursor from pagination.next. Bound to tenant, filters, window, page size, and configured collection/index generation.
     */
    @JsonProperty("start")
    public Optional<String> getStart() {
        return start;
    }

    /**
     * @return Maximum unique events returned. A short page may have a next cursor.
     */
    @JsonProperty("size")
    public Optional<Integer> getSize() {
        return size;
    }

    /**
     * @return Exact event type.
     */
    @JsonProperty("type")
    public Optional<String> getType() {
        return type;
    }

    /**
     * @return Exact trace ID.
     */
    @JsonProperty("trace_id")
    public Optional<String> getTraceId() {
        return traceId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EventsListRequest && equalTo((EventsListRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EventsListRequest other) {
        return startDate.equals(other.startDate)
                && endDate.equals(other.endDate)
                && start.equals(other.start)
                && size.equals(other.size)
                && type.equals(other.type)
                && traceId.equals(other.traceId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.startDate, this.endDate, this.start, this.size, this.type, this.traceId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<OffsetDateTime> startDate = Optional.empty();

        private Optional<OffsetDateTime> endDate = Optional.empty();

        private Optional<String> start = Optional.empty();

        private Optional<Integer> size = Optional.empty();

        private Optional<String> type = Optional.empty();

        private Optional<String> traceId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(EventsListRequest other) {
            startDate(other.getStartDate());
            endDate(other.getEndDate());
            start(other.getStart());
            size(other.getSize());
            type(other.getType());
            traceId(other.getTraceId());
            return this;
        }

        /**
         * <p>Inclusive timestamp; defaults to 24 hours before end_date, shortened to tenant entitlement. An earlier value is raised to the oldest visible instant. ISO 8601 with timezone, at most millisecond precision. Must not be after end_date.</p>
         */
        @JsonSetter(value = "start_date", nulls = Nulls.SKIP)
        public Builder startDate(Optional<OffsetDateTime> startDate) {
            this.startDate = startDate;
            return this;
        }

        public Builder startDate(OffsetDateTime startDate) {
            this.startDate = Optional.ofNullable(startDate);
            return this;
        }

        /**
         * <p>Exclusive timestamp; defaults to request time. A future value is lowered to request time. A window with no visible history returns an empty page.</p>
         */
        @JsonSetter(value = "end_date", nulls = Nulls.SKIP)
        public Builder endDate(Optional<OffsetDateTime> endDate) {
            this.endDate = endDate;
            return this;
        }

        public Builder endDate(OffsetDateTime endDate) {
            this.endDate = Optional.ofNullable(endDate);
            return this;
        }

        /**
         * <p>Opaque cursor from pagination.next. Bound to tenant, filters, window, page size, and configured collection/index generation.</p>
         */
        @JsonSetter(value = "start", nulls = Nulls.SKIP)
        public Builder start(Optional<String> start) {
            this.start = start;
            return this;
        }

        public Builder start(String start) {
            this.start = Optional.ofNullable(start);
            return this;
        }

        /**
         * <p>Maximum unique events returned. A short page may have a next cursor.</p>
         */
        @JsonSetter(value = "size", nulls = Nulls.SKIP)
        public Builder size(Optional<Integer> size) {
            this.size = size;
            return this;
        }

        public Builder size(Integer size) {
            this.size = Optional.ofNullable(size);
            return this;
        }

        /**
         * <p>Exact event type.</p>
         */
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<String> type) {
            this.type = type;
            return this;
        }

        public Builder type(String type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * <p>Exact trace ID.</p>
         */
        @JsonSetter(value = "trace_id", nulls = Nulls.SKIP)
        public Builder traceId(Optional<String> traceId) {
            this.traceId = traceId;
            return this;
        }

        public Builder traceId(String traceId) {
            this.traceId = Optional.ofNullable(traceId);
            return this;
        }

        public EventsListRequest build() {
            return new EventsListRequest(startDate, endDate, start, size, type, traceId, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
