/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.sessions;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.IdempotentRequestOptions;
import com.basistheory.resources.sessions.requests.AuthorizeSessionRequest;
import com.basistheory.types.CreateSessionResponse;

public class SessionsClient {
    protected final ClientOptions clientOptions;

    private final RawSessionsClient rawClient;

    public SessionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawSessionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawSessionsClient withRawResponse() {
        return this.rawClient;
    }

    public CreateSessionResponse create() {
        return this.rawClient.create().body();
    }

    public CreateSessionResponse create(IdempotentRequestOptions requestOptions) {
        return this.rawClient.create(requestOptions).body();
    }

    public void authorize(AuthorizeSessionRequest request) {
        this.rawClient.authorize(request).body();
    }

    public void authorize(AuthorizeSessionRequest request, IdempotentRequestOptions requestOptions) {
        this.rawClient.authorize(request, requestOptions).body();
    }
}
