name: ci

on:
  pull_request:
    branches: [master]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        id: setup-jre
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64

      - name: Compile
        run: ./gradlew compileJava

  test:
    needs: [ compile ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        id: setup-jre
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64

      - name: Test
        run: ./gradlew test
        env:
          BT_API_URL: https://api.flock-dev.com
          BT_MGT_API_KEY: ${{ secrets.BT_SDK_INT_TEST_MGT_API_KEY }}
          BT_PVT_API_KEY: ${{ secrets.BT_SDK_INT_TEST_PVT_API_KEY }}
          BT_MGT_TEST_API_KEY: ${{ secrets.BT_SDK_INT_TEST_MGT_TEST_API_KEY }}
          BT_PVT_TEST_API_KEY: ${{ secrets.BT_SDK_INT_TEST_PVT_TEST_API_KEY }}

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: problems-report
          path: build/reports/problems/problems-report.html
          retention-days: 1

